# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 19
      uses: actions/setup-node@v3
      with:
        node-version: 19
    - run: npm install
    - run: npm run compile-xsl
      continue-on-error: true
    - run: npm run build --if-present
    - run: npm test
